# Generated by Django 3.1 on 2020-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello_world', models.TextField(verbose_name='Базовое приветствие бота')),
            ],
        ),
    ]
