# Generated by Django 3.1 on 2020-09-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help', models.TextField(verbose_name='Перелік можливостей бота')),
            ],
            options={
                'verbose_name': 'Допомога',
                'verbose_name_plural': 'Допомога',
            },
        ),
        migrations.AlterModelOptions(
            name='greeting',
            options={'verbose_name': 'Привітання', 'verbose_name_plural': 'Привітання'},
        ),
        migrations.AlterField(
            model_name='greeting',
            name='hello_world',
            field=models.TextField(verbose_name='Базове привітання бота'),
        ),
    ]
